[World]
Name=Duplicate CO Ini Test
Author=Lit Knob
Format=2
HoloFix=True

;Different sprite once
[Custom Object 1]
Image=Frames.png
[Custom Object 2]
Image=Frames.png
[Custom Object 2]
Image=Frames R.png

;Different sprite, resolution, and offset
[Custom Object 3]
Image=Frames 2.png
Tile Width=48
Offset X=12

[Custom Object 4]
Image=Frames 2.png
Tile Height=48
Offset y=12

[Custom Object 4]
Image=Frames 3.png
Tile width=48
Offset X=12

;Different sprite x3
[Custom Object 5]
Image=Frames 4.png
[Custom Object 6]
Image=Frames 4.png
[Custom Object 6]
Image=Frames 5.png
[Custom Object 6]
Image=Frames 6.png
[Custom Object 6]
Image=Frames 7.png

;Different ending frame and speed
[Custom Object 7]
Image=Frames.png
Init AnimTo=8
Init AnimSpeed=240

[Custom Object 8]
Image=Frames.png
Init AnimTo=8
Init AnimSpeed=240

[Custom Object 8]
Image=Frames.png
Init AnimTo=4
Init AnimSpeed=160

[Custom Object 8]
Image=Frames.png
Init AnimTo=2
Init AnimSpeed=80

[Custom Object 8]
Image=Frames.png
Init AnimTo=1
Init AnimSpeed=40

;Different Loop Back To
[Custom Object 9]
Image=Frames.png
Init AnimLoopBack=8
Init AnimTo=8
[Custom Object 10]
Image=Frames.png
Init AnimLoopBack=8
Init AnimTo=8
[Custom Object 10]
Image=Frames.png
Init AnimLoopBack=6
Init AnimTo=8

;Different Times To Play
[Custom Object 11]
Image=Frames.png
Init AnimTo=8
[Custom Object 12]
Image=Frames.png
Init AnimTo=8
[Custom Object 12]
Image=Frames.png
Init AnimTo=8
Init AnimRepeat=1

;Different bank and object
[Custom Object 13]
Image=Frames.png
Bank=4
Object=18
[Custom Object 14]
Image=Frames.png
Bank=4
Object=18
[Custom Object 14]
Image=Frames.png
Bank=2
Object=1

;Different misc (and frame size test)
[Custom Object 15]
Image=Frames 2.png
Init AnimTo=1
Offset X=12
Init AnimSpeed=80
[Custom Object 16]
Image=Frames 2.png
Init AnimTo=1
Offset X=12
Init AnimSpeed=80
[Custom Object 16]
Image=Frames.png
Init AnimTo=2
Init AnimSpeed=40
