[World]
Name=CO Speed Test
Author=Lit Knob
Format=4
HoloFix=True

;Half speed test
[Custom Object 1]
Image=Frames 2.png
Init AnimTo=3
Init AnimSpeed=20
[Custom Object 2]
Image=Frames 2.png
Init AnimTo=3
Init AnimSpeed=40

;Default speed test
[Custom Object 3]
Image=Frames.png
Init AnimTo=8
[Custom Object 4]
Image=Frames.png
Init AnimTo=8
Init AnimSpeed=500

;1/5 speed test
[Custom Object 6]
Image=Frames 2.png
Init AnimTo=4
Init AnimSpeed=100
[Custom Object 7]
Image=Frames 2.png
Init AnimTo=4
Init AnimSpeed=20

;Max speed test
[Custom Object 8]
Image=Frames.png
Init AnimTo=8
Init AnimSpeed=1000
[Custom Object 9]
Image=Frames.png
Init AnimTo=8
Init AnimSpeed=2000
[Custom Object 10]
Image=Frames.png
Init AnimTo=8
Init AnimSpeed=1001
