[World]
Name=Supported OCO Test
Author=Lit Knob
Format=4
HoloFix=True

;Bank0 passes
[Custom Object 1]
Image=0-3.png
Object=3
[Custom Object 2]
Image=0-4.png
Object=4
[Custom Object 3]
Image=0-5.png
Object=5
[Custom Object 4]
Image=0-6.png
Object=6
[Custom Object 5]
Image=0-7.png
Object=7
[Custom Object 6]
Image=0-8.png
Object=8
[Custom Object 7]
Image=0-9 Static.png
Object=9
[Custom Object 8]
Image=0-10.png
Object=10
[Custom Object 9]
Image=0-21 Static.png
Object=21
[Custom Object 10]
Image=0-22 Static.png
Object=22
[Custom Object 11]
Image=0-23 Static.png
Object=23
[Custom Object 12]
Image=0-24 Static.png
Object=24
[Custom Object 13]
Image=0-35.png
Object=35

;Bank1 passes
[Custom Object 14]
Image=1-1.png
Bank=1
Object=1
[Custom Object 15]
Image=1-2.png
Bank=1
Object=2
[Custom Object 16]
Image=1-3.png
Bank=1
Object=3
[Custom Object 17]
Image=1-4.png
Bank=1
Object=4
[Custom Object 18]
Image=1-5.png
Bank=1
Object=5
[Custom Object 19]
Image=1-6.png
Bank=1
Object=6
[Custom Object 20]
Image=1-10.png
Bank=1
Object=10
[Custom Object 21]
Image=1-12.png
Bank=1
Object=12
[Custom Object 22]
Image=1-13.png
Bank=1
Object=13
[Custom Object 23]
Image=1-14.png
Bank=1
Object=14
[Custom Object 24]
Image=1-15.png
Bank=1
Object=15
[Custom Object 25]
Image=1-16.png
Bank=1
Object=16
[Custom Object 26]
Image=1-19.png
Bank=1
Object=19
[Custom Object 27]
Image=1-20.png
Bank=1
Object=20
[Custom Object 28]
Image=1-22.png
Bank=1
Object=22
[Custom Object 29]
Image=1-23.png
Bank=1
Object=23

;Bank2 passes
[Custom Object 30]
Image=2-1.png
Bank=2
Object=1
[Custom Object 31]
Image=2-2.png
Bank=2
Object=2
[Custom Object 32]
Image=2-3.png
Bank=2
Object=3
[Custom Object 33]
Image=2-4.png
Bank=2
Object=4
[Custom Object 34]
Image=2-5.png
Bank=2
Object=5
[Custom Object 35]
Image=2-6.png
Bank=2
Object=6
[Custom Object 36]
Image=2-7.png
Bank=2
Object=7
[Custom Object 37]
Image=2-9.png
Bank=2
Object=9
[Custom Object 38]
Image=2-10.png
Bank=2
Object=10
[Custom Object 39]
Image=2-11.png
Bank=2
Object=11
[Custom Object 40]
Image=2-12.png
Bank=2
Object=12
[Custom Object 41]
Image=2-14.png
Bank=2
Object=14
[Custom Object 42]
Image=2-15 Propeller Dude.png
Bank=2
Object=15
[Custom Object 43]
Image=2-16 Propeller Child.png
Bank=2
Object=16
[Custom Object 44]
Image=2-17 Propeller Child 2.png
Bank=2
Object=17
[Custom Object 45]
Image=2-20.png
Bank=2
Object=20
[Custom Object 46]
Image=2-21.png
Bank=2
Object=21
[Custom Object 47]
Image=2-22.png
Bank=2
Object=22
[Custom Object 48]
Image=2-24.png
Bank=2
Object=24
[Custom Object 49]
Image=2-25.png
Bank=2
Object=25
[Custom Object 50]
Image=2-26.png
Bank=2
Object=26
[Custom Object 51]
Image=2-27.png
Bank=2
Object=27
[Custom Object 52]
Image=2-28.png
Bank=2
Object=28
[Custom Object 53]
Image=2-29.png
Bank=2
Object=29
[Custom Object 54]
Image=2-30.png
Bank=2
Object=30
[Custom Object 55]
Image=2-31.png
Bank=2
Object=31
[Custom Object 56]
Image=2-32 Fast Homing Square.png
Bank=2
Object=32

;Bank3 passes
[Custom Object 57]
Image=3-1.png
Bank=3
Object=1
[Custom Object 58]
Image=3-2.png
Bank=3
Object=2
[Custom Object 59]
Image=3-3.png
Bank=3
Object=3
[Custom Object 60]
Image=3-4.png
Bank=3
Object=4
[Custom Object 61]
Image=3-5.png
Bank=3
Object=5
[Custom Object 62]
Image=3-6.png
Bank=3
Object=6
[Custom Object 63]
Image=3-7.png
Bank=3
Object=7
[Custom Object 64]
Image=3-8.png
Bank=3
Object=8
[Custom Object 65]
Image=3-9.png
Bank=3
Object=9
[Custom Object 66]
Image=3-10.png
Bank=3
Object=10
[Custom Object 67]
Image=3-11.png
Bank=3
Object=11
[Custom Object 68]
Image=3-12.png
Bank=3
Object=12
[Custom Object 69]
Image=3-13.png
Bank=3
Object=13
[Custom Object 70]
Image=3-14 Forest Girl 2.png
Bank=3
Object=14
[Custom Object 71]
Image=3-15.png
Bank=3
Object=15
[Custom Object 72]
Image=3-16.png
Bank=3
Object=16
[Custom Object 73]
Image=3-17.png
Bank=3
Object=17
[Custom Object 74]
Image=3-18.png
Bank=3
Object=18
[Custom Object 75]
Image=3-19.png
Bank=3
Object=19
[Custom Object 76]
Image=3-20.png
Bank=3
Object=20
[Custom Object 77]
Image=3-21.png
Bank=3
Object=21
[Custom Object 78]
Image=3-22.png
Bank=3
Object=22
[Custom Object 79]
Image=3-23.png
Bank=3
Object=23
[Custom Object 80]
Image=3-24.png
Bank=3
Object=24
[Custom Object 81]
Image=3-25.png
Bank=3
Object=25
[Custom Object 82]
Image=3-26 Forest Dude.png
Bank=3
Object=26
[Custom Object 83]
Image=3-27.png
Bank=3
Object=27
[Custom Object 84]
Image=3-28.png
Bank=3
Object=28
[Custom Object 85]
Image=3-30.png
Bank=3
Object=30
[Custom Object 86]
Image=3-31.png
Bank=3
Object=31
[Custom Object 87]
Image=3-32.png
Bank=3
Object=32
[Custom Object 88]
Image=3-33.png
Bank=3
Object=33
[Custom Object 89]
Image=3-34.png
Bank=3
Object=34
[Custom Object 90]
Image=3-35.png
Bank=3
Object=35
[Custom Object 91]
Image=3-36.png
Bank=3
Object=36
[Custom Object 92]
Image=3-37.png
Bank=3
Object=37
[Custom Object 93]
Image=3-38 Cave Girl.png
Bank=3
Object=38
[Custom Object 94]
Image=3-39.png
Bank=3
Object=39
[Custom Object 95]
Image=3-40.png
Bank=3
Object=40
[Custom Object 96]
Image=3-41 Sister.png
Bank=3
Object=41
[Custom Object 97]
Image=3-42.png
Bank=3
Object=42
[Custom Object 98]
Image=3-43.png
Bank=3
Object=43
[Custom Object 99]
Image=3-44.png
Bank=3
Object=44

;Bank4 passes
[Custom Object 100]
Image=4-1.png
Bank=4
Object=1
[Custom Object 101]
Image=4-2.png
Bank=4
Object=2
[Custom Object 102]
Image=4-3.png
Bank=4
Object=3
[Custom Object 103]
Image=4-4.png
Bank=4
Object=4
[Custom Object 104]
Image=4-5.png
Bank=4
Object=5
[Custom Object 105]
Image=4-6.png
Bank=4
Object=6
[Custom Object 106]
Image=4-7.png
Bank=4
Object=7
[Custom Object 107]
Image=4-8.png
Bank=4
Object=8
[Custom Object 108]
Image=4-9 Spider.png
Bank=4
Object=9
Tile Width=48
[Custom Object 109]
Image=4-10.png
Bank=4
Object=10
[Custom Object 110]
Image=4-11.png
Bank=4
Object=11
[Custom Object 111]
Image=4-12.png
Bank=4
Object=12
[Custom Object 112]
Image=4-13.png
Bank=4
Object=13
[Custom Object 113]
Image=4-14.png
Bank=4
Object=14
[Custom Object 114]
Image=4-15.png
Bank=4
Object=15
[Custom Object 115]
Image=4-16.png
Bank=4
Object=16
[Custom Object 116]
Image=4-17.png
Bank=4
Object=17
[Custom Object 117]
Image=4-18.png
Bank=4
Object=18
[Custom Object 118]
Image=4-19.png
Bank=4
Object=19
[Custom Object 119]
Image=4-20.png
Bank=4
Object=20
[Custom Object 120]
Image=4-21.png
Bank=4
Object=21
[Custom Object 121]
Image=4-22.png
Bank=4
Object=22

;Bank6 passes
[Custom Object 122]
Image=6-1.png
Bank=6
Object=1
Tile Width=96
[Custom Object 123]
Image=6-2 Labyrint Spike.png
Bank=6
Object=2
[Custom Object 124]
Image=6-3 Random Labyrint Spike.png
Bank=6
Object=3
[Custom Object 125]
Image=6-4 Fast Labyrint Spike.png
Bank=6
Object=4
[Custom Object 126]
Image=6-5.png
Bank=6
Object=5
Tile Width=48
Tile Height=48
[Custom Object 127]
Image=6-6.png
Bank=6
Object=6
[Custom Object 128]
Image=6-7.png
Bank=6
Object=7
[Custom Object 129]
Image=6-8.png
Bank=6
Object=8
[Custom Object 130]
Image=6-9.png
Bank=6
Object=9
[Custom Object 131]
Image=6-10.png
Bank=6
Object=10
[Custom Object 132]
Image=6-11.png
Bank=6
Object=11
[Custom Object 133]
Image=6-12.png
Bank=6
Object=12
[Custom Object 134]
Image=6-13.png
Bank=6
Object=13
[Custom Object 135]
Image=6-14 Up Spikes Static.png
Bank=6
Object=14
[Custom Object 136]
Image=6-15 Down Spikes Static.png
Bank=6
Object=15
[Custom Object 137]
Image=6-16 Left Spikes Static.png
Bank=6
Object=16
[Custom Object 138]
Image=6-17 Right Spikes Static.png
Bank=6
Object=17

;Bank8 passes (8:7 fixed)
[Custom Object 139]
Image=8-6.png
Bank=8
Object=6
[Custom Object 140]
Image=8-7 Multiple Fires.png
Bank=8
Object=7
Tile Width=48
Offset X=12
[Custom Object 141]
Image=8-8.png
Bank=8
Object=8
[Custom Object 142]
Image=8-9.png
Bank=8
Object=9
[Custom Object 143]
Image=8-10.png
Bank=8
Object=10
[Custom Object 144]
Image=8-11.png
Bank=8
Object=11
[Custom Object 145]
Image=8-13.png
Bank=8
Object=13
[Custom Object 146]
Image=8-14.png
Bank=8
Object=14

;Bank9 passes
[Custom Object 147]
Image=9-1.png
Bank=9
Object=1
[Custom Object 148]
Image=9-2.png
Bank=9
Object=2
[Custom Object 149]
Image=9-3.png
Bank=9
Object=3
[Custom Object 150]
Image=9-4.png
Bank=9
Object=4
[Custom Object 151]
Image=9-5.png
Bank=9
Object=5

;Bank10 passes
[Custom Object 152]
Image=10-1.png
Bank=10
Object=1
[Custom Object 153]
Image=10-2.png
Bank=10
Object=2
[Custom Object 154]
Image=10-3.png
Bank=10
Object=3
[Custom Object 155]
Image=10-4.png
Bank=10
Object=4
[Custom Object 156]
Image=10-5.png
Bank=10
Object=5
[Custom Object 157]
Image=10-6.png
Bank=10
Object=6
[Custom Object 158]
Image=10-7.png
Bank=10
Object=7
[Custom Object 159]
Image=10-8.png
Bank=10
Object=8
[Custom Object 160]
Image=10-9.png
Bank=10
Object=9
[Custom Object 161]
Image=10-10.png
Bank=10
Object=10
[Custom Object 162]
Image=10-11.png
Bank=10
Object=11
[Custom Object 163]
Image=10-12.png
Bank=10
Object=12
[Custom Object 164]
Image=10-13.png
Bank=10
Object=13

;Bank11 passes
[Custom Object 165]
Image=11-1.png
Bank=11
Object=1
[Custom Object 166]
Image=11-2.png
Bank=11
Object=2
[Custom Object 167]
Image=11-3.png
Bank=11
Object=3
[Custom Object 168]
Image=11-4.png
Bank=11
Object=4
[Custom Object 169]
Image=11-5.png
Bank=11
Object=5
[Custom Object 170]
Image=11-6.png
Bank=11
Object=6
[Custom Object 171]
Image=11-7.png
Bank=11
Object=7
[Custom Object 172]
Image=11-8.png
Bank=11
Object=8
[Custom Object 173]
Image=11-9.png
Bank=11
Object=9
[Custom Object 174]
Image=11-10.png
Bank=11
Object=10
[Custom Object 175]
Image=11-11.png
Bank=11
Object=11

;Bank13 passes (13:1, 2, 14 fixed)
[Custom Object 176]
Image=13-1.png
Bank=13
Object=1
[Custom Object 177]
Image=13-2.png
Bank=13
Object=2
[Custom Object 178]
Image=13-3.png
Bank=13
Object=3
Tile Height=96
[Custom Object 179]
Image=13-4.png
Bank=13
Object=4
Tile Width=48
Tile Height=48
[Custom Object 180]
Image=13-5.png
Bank=13
Object=5
[Custom Object 181]
Image=13-6.png
Bank=13
Object=6
[Custom Object 182]
Image=13-7,8,9 Horizontal Laser.png
Bank=13
Object=7
[Custom Object 183]
Image=13-7,8,9 Horizontal Laser.png
Bank=13
Object=8
[Custom Object 184]
Image=13-7,8,9 Horizontal Laser.png
Bank=13
Object=9
[Custom Object 185]
Image=13-10,11,12 Vertical Laser.png
Bank=13
Object=10
[Custom Object 186]
Image=13-10,11,12 Vertical Laser.png
Bank=13
Object=11
[Custom Object 187]
Image=13-10,11,12 Vertical Laser.png
Bank=13
Object=12
[Custom Object 188]
Image=13-13.png
Bank=13
Object=13
[Custom Object 189]
Image=13-14.png
Bank=13
Object=14

;Bank14 passes
[Custom Object 190]
Image=14-1.png
Bank=14
Object=1
[Custom Object 191]
Image=14-2.png
Bank=14
Object=2
[Custom Object 192]
Image=14-3.png
Bank=14
Object=3
[Custom Object 193]
Image=14-4.png
Bank=14
Object=4
[Custom Object 194]
Image=14-5.png
Bank=14
Object=5
[Custom Object 195]
Image=14-6.png
Bank=14
Object=6
[Custom Object 196]
Image=14-7.png
Bank=14
Object=7
[Custom Object 197]
Image=14-8.png
Bank=14
Object=8
[Custom Object 198]
Image=14-9.png
Bank=14
Object=9
[Custom Object 199]
Image=14-10.png
Bank=14
Object=10
[Custom Object 200]
Image=14-11.png
Bank=14
Object=11
[Custom Object 201]
Image=14-12.png
Bank=14
Object=12
[Custom Object 202]
Image=14-13.png
Bank=14
Object=13
[Custom Object 203]
Image=14-14.png
Bank=14
Object=14
[Custom Object 204]
Image=14-15.png
Bank=14
Object=15
[Custom Object 205]
Image=14-16.png
Bank=14
Object=16
Tile Height=72
Tile Width=120
Offset Y=-24
[Custom Object 206]
Image=14-17.png
Bank=14
Object=17
[Custom Object 207]
Image=14-18.png
Bank=14
Object=18
Tile Width=120
Tile Height=72
Offset Y=24
[Custom Object 208]
Image=14-19.png
Bank=14
Object=19
[Custom Object 209]
Image=14-20.png
Bank=14
Object=20
[Custom Object 210]
Image=14-21.png
Bank=14
Object=21
[Custom Object 211]
Image=14-22.png
Bank=14
Object=22
[Custom Object 212]
Image=14-23.png
Bank=14
Object=23
[Custom Object 213]
Image=14-24.png
Bank=14
Object=24

;Bank15 passes
[Custom Object 214]
Image=15-5.png
Bank=15
Object=5
[Custom Object 215]
Image=15-12.png
Bank=15
Object=12
[Custom Object 216]
Image=15-22.png
Bank=15
Object=22
Tile Height=48
[Custom Object 217]
Image=15-23.png
Bank=15
Object=23
[Custom Object 218]
Image=15-24.png
Bank=15
Object=24
[Custom Object 219]
Image=15-27.png
Bank=15
Object=27
[Custom Object 220]
Image=15-28.png
Bank=15
Object=28
[Custom Object 221]
Image=15-29.png
Bank=15
Object=29
[Custom Object 222]
Image=15-30.png
Bank=15
Object=30
[Custom Object 223]
Image=15-31.png
Bank=15
Object=31
[Custom Object 224]
Image=15-32.png
Bank=15
Object=32
[Custom Object 225]
Image=15-33.png
Bank=15
Object=33
[Custom Object 226]
Image=15-34.png
Bank=15
Object=34
[Custom Object 227]
Image=15-35.png
Bank=15
Object=35
[Custom Object 228]
Image=15-36.png
Bank=15
Object=36
[Custom Object 229]
Image=15-37.png
Bank=15
Object=37
[Custom Object 230]
Image=15-38.png
Bank=15
Object=38

;Bank17 passes (17:9 fixed)
[Custom Object 231]
Image=17-1.png
Bank=17
Object=1
[Custom Object 232]
Image=17-2.png
Bank=17
Object=2
[Custom Object 233]
Image=17-3.png
Bank=17
Object=3
Tile Height=48
[Custom Object 234]
Image=17-4.png
Bank=17
Object=4
[Custom Object 235]
Image=17-5.png
Bank=17
Object=5
[Custom Object 236]
Image=17-6.png
Bank=17
Object=6
[Custom Object 237]
Image=17-7.png
Bank=17
Object=7
[Custom Object 238]
Image=17-8.png
Bank=17
Object=8
[Custom Object 239]
Image=17-9.png
Bank=17
Object=9
[Custom Object 240]
Image=17-10.png
Bank=17
Object=10
Tile Width=120
Tile Height=72
Offset Y=-24
[Custom Object 241]
Image=17-11.png
Bank=17
Object=11
Tile Width=72
Tile Height=120
Offset X=24
[Custom Object 242]
Image=17-12.png
Bank=17
Object=12
Tile Width=72
Tile Height=120
Offset X=-24

;Bank18 passes (18:5 fixed)
[Custom Object 243]
Image=18-1.png
Bank=18
Object=1
[Custom Object 244]
Image=18-2,5.png
Bank=18
Object=2
[Custom Object 245]
Image=18-3.png
Bank=18
Object=3
[Custom Object 246]
Image=18-4.png
Bank=18
Object=4
[Custom Object 247]
Image=18-2,5.png
Bank=18
Object=5
[Custom Object 248]
Image=18-6.png
Bank=18
Object=6
Tile Height=48

;Bank19 passes
[Custom Object B1]
Image=19-1.png
Bank=19
Object=1
[Custom Object B2]
Image=19-2.png
Bank=19
Object=2
[Custom Object B3]
Image=19-3.png
Bank=19
Object=3
[Custom Object B4]
Image=19-5.png
Bank=19
Object=5
[Custom Object B5]
Image=19-6.png
Bank=19
Object=6
[Custom Object B6]
Image=19-7.png
Bank=19
Object=7
[Custom Object B7]
Image=19-8.png
Bank=19
Object=8
[Custom Object B8]
Image=19-9.png
Bank=19
Object=9
[Custom Object B9]
Image=19-10.png
Bank=19
Object=10
[Custom Object B10]
Image=19-11.png
Bank=19
Object=11
[Custom Object B11]
Image=19-12.png
Bank=19
Object=12
[Custom Object B12]
Image=19-13.png
Bank=19
Object=13
[Custom Object B13]
Image=19-14.png
Bank=19
Object=14
[Custom Object B14]
Image=19-15.png
Bank=19
Object=15
[Custom Object B15]
Image=19-16.png
Bank=19
Object=16
[Custom Object B16]
Image=19-17.png
Bank=19
Object=17
[Custom Object B17]
Image=19-18.png
Bank=19
Object=18
[Custom Object B18]
Image=19-19.png
Bank=19
Object=19
[Custom Object B19]
Image=19-20.png
Bank=19
Object=20
[Custom Object B20]
Image=19-21.png
Bank=19
Object=21
[Custom Object B21]
Image=19-22.png
Bank=19
Object=22
[Custom Object B22]
Image=19-23.png
Bank=19
Object=23
[Custom Object B23]
Image=19-24.png
Bank=19
Object=24
[Custom Object B24]
Image=19-25.png
Bank=19
Object=25
[Custom Object B25]
Image=19-26.png
Bank=19
Object=26
[Custom Object B26]
Image=19-27.png
Bank=19
Object=27
[Custom Object B27]
Image=19-28.png
Bank=19
Object=28
[Custom Object B28]
Image=19-29.png
Bank=19
Object=29
[Custom Object B29]
Image=19-30.png
Bank=19
Object=30
[Custom Object B30]
Image=19-31.png
Bank=19
Object=31
Tile Width=48
Tile Height=48
[Custom Object B31]
Image=19-32.png
Bank=19
Object=32
[Custom Object B32]
Image=19-33.png
Bank=19
Object=33
[Custom Object B33]
Image=19-34.png
Bank=19
Object=34
[Custom Object B34]
Image=19-35.png
Bank=19
Object=35
[Custom Object B35]
Image=19-36.png
Bank=19
Object=36
[Custom Object B36]
Image=19-37.png
Bank=19
Object=37
[Custom Object B37]
Image=19-38.png
Bank=19
Object=38
[Custom Object B38]
Image=19-39.png
Bank=19
Object=39
[Custom Object B39]
Image=19-40.png
Bank=19
Object=40
[Custom Object B40]
Image=19-41.png
Bank=19
Object=41
[Custom Object B41]
Image=19-42.png
Bank=19
Object=42
[Custom Object B42]
Image=19-43.png
Bank=19
Object=43
[Custom Object B43]
Image=19-44.png
Bank=19
Object=44
[Custom Object B44]
Image=19-45.png
Bank=19
Object=45
[Custom Object B45]
Image=19-46.png
Bank=19
Object=46
[Custom Object B46]
Image=19-47.png
Bank=19
Object=47
[Custom Object B47]
Image=19-48.png
Bank=19
Object=48
[Custom Object B48]
Image=19-49.png
Bank=19
Object=49
[Custom Object B49]
Image=19-50.png
Bank=19
Object=50
Tile Height=48
[Custom Object B50]
Image=Artifact1.png
Bank=19
Object=151
[Custom Object B51]
Image=Artifact1.png
Bank=19
Object=152
[Custom Object B52]
Image=Artifact1.png
Bank=19
Object=153
[Custom Object B53]
Image=Artifact1.png
Bank=19
Object=154
[Custom Object B54]
Image=Artifact1.png
Bank=19
Object=155
[Custom Object B55]
Image=Artifact1.png
Bank=19
Object=156
[Custom Object B56]
Image=Artifact1.png
Bank=19
Object=157
[Custom Object B57]
Image=Artifact2.png
Bank=19
Object=158
[Custom Object B58]
Image=Artifact2.png
Bank=19
Object=159
[Custom Object B59]
Image=Artifact2.png
Bank=19
Object=160
[Custom Object B60]
Image=Artifact2.png
Bank=19
Object=161
[Custom Object B61]
Image=Artifact2.png
Bank=19
Object=162
[Custom Object B62]
Image=Artifact2.png
Bank=19
Object=163
[Custom Object B63]
Image=Artifact2.png
Bank=19
Object=164
[Custom Object B64]
Image=Artifact3.png
Bank=19
Object=165
[Custom Object B65]
Image=Artifact3.png
Bank=19
Object=166
[Custom Object B66]
Image=Artifact3.png
Bank=19
Object=167
[Custom Object B67]
Image=Artifact3.png
Bank=19
Object=168
[Custom Object B68]
Image=Artifact3.png
Bank=19
Object=169
[Custom Object B69]
Image=Artifact3.png
Bank=19
Object=170
[Custom Object B70]
Image=Artifact3.png
Bank=19
Object=171
[Custom Object B71]
Image=Artifact4.png
Bank=19
Object=172
[Custom Object B72]
Image=Artifact4.png
Bank=19
Object=173
[Custom Object B73]
Image=Artifact4.png
Bank=19
Object=174
[Custom Object B74]
Image=Artifact4.png
Bank=19
Object=175
[Custom Object B75]
Image=Artifact4.png
Bank=19
Object=176
[Custom Object B76]
Image=Artifact4.png
Bank=19
Object=177
[Custom Object B77]
Image=Artifact4.png
Bank=19
Object=178
[Custom Object B78]
Image=Artifact5.png
Bank=19
Object=179
[Custom Object B79]
Image=Artifact5.png
Bank=19
Object=180
[Custom Object B80]
Image=Artifact5.png
Bank=19
Object=181
[Custom Object B81]
Image=Artifact5.png
Bank=19
Object=182
[Custom Object B82]
Image=Artifact5.png
Bank=19
Object=183
[Custom Object B83]
Image=Artifact5.png
Bank=19
Object=184
[Custom Object B84]
Image=Artifact5.png
Bank=19
Object=185
[Custom Object B85]
Image=Artifact6.png
Bank=19
Object=186
[Custom Object B86]
Image=Artifact6.png
Bank=19
Object=187
[Custom Object B87]
Image=Artifact6.png
Bank=19
Object=188
[Custom Object B88]
Image=Artifact6.png
Bank=19
Object=189
[Custom Object B89]
Image=Artifact6.png
Bank=19
Object=190
[Custom Object B90]
Image=Artifact6.png
Bank=19
Object=191
[Custom Object B91]
Image=Artifact6.png
Bank=19
Object=192
[Custom Object B92]
Image=Artifact7.png
Bank=19
Object=193
[Custom Object B93]
Image=Artifact7.png
Bank=19
Object=194
[Custom Object B94]
Image=Artifact7.png
Bank=19
Object=195
[Custom Object B95]
Image=Artifact7.png
Bank=19
Object=196
[Custom Object B96]
Image=Artifact7.png
Bank=19
Object=197
[Custom Object B97]
Image=Artifact7.png
Bank=19
Object=198
[Custom Object B98]
Image=Artifact7.png
Bank=19
Object=199
