[World]
Name=CO Frame Size Test
Author=Lit Knob
Format=4
HoloFix=True

;Frames (1 wins)
[Custom Object 1]
Image=Frames.png
[Custom Object 2]
Image=Frames.png
Tile Width=48
Tile Height=48
Offset X=12
Offset Y=12
[Custom Object 3]
Image=frAmEs.png
Tile Width=72
Tile Height=72
Offset X=24
Offset Y=24
[Custom Object 4]
Image=FRAMES.png
Tile Width=48
Offset X=12

;Frames 2 (5 wins)
[Custom Object 6]
Image=Frames 2.png
Tile Height=72
Offset Y=24
[Custom Object 5]
Image=fRAMES 2.png
Tile Height=48
Offset Y=12

;Frames 4 (B1 Wins)
[Custom Object 7]
Image=Frames 4.png
[Custom Object B1]
Image=Frames 4.png
Tile Height=72
Offset Y=24

;Frames 6 (8 wins)
[Custom Object 8]
Image=Frames 6.png
Tile Width=48
Offset X=12
[Custom Object B8]
Image=Frames 6.png

;Frames 7 (B9 wins)
[Custom Object B9]
Image=Frames 7.png
Tile Width=48
Tile Height=48
Offset X=12
Offset Y=12
[Custom Object 10]
Image=Frames 7.png
